# Note:
#
# Please keep rules alphabetized within their sections (Style, Metrics, etc)
# Please keep sections alphabetized and separated from other sections

require:
  - rubocop-minitest

AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - gemfiles/**/*

Layout/LineLength:
  Max: 120

Metrics/ClassLength:
  Exclude:
    - test/**/*

Metrics/MethodLength:
  Exclude:
    - test/**/*

Metrics/ModuleLength:
  Exclude:
    - test/**/*

Style/Documentation:
  Enabled: false
